config/routes.rb
Rails.application.routes.draw do

  root 'guild#show'

  resources :members, only: [:new, :create, :update, :destroy, :show, :index] do
    collection do
      get 'ids'
    end
  end

  post 'members/:id/update_dps' => 'members#update_dps'
  post 'members/:id/update_sims' => 'members#update_sims'

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :member

  def self.slots
    [
      :head,
      :neck,
      :shoulder,
      :back,
      :chest,
      :wrist,
      :hands,
      :waist,
      :legs,
      :feet,
      :finger_1,
      :finger_2,
      :trinket_1,
      :trinket_2,
      :main_hand,
      :off_hand
    ]
  end

  def self.color_for_ilvl(ilvl)
    rbg = "rgba(0, 129 , 255,"
    rbg = "rgba(198, 0 , 255," if ilvl >= 184
    rbg = "rgba(255, 128, 0," if ilvl >= 210

    # opacity = ((ilvl - 800)/35)*0.4 + 0.3
    # opacity = ((ilvl - 835)/15)*0.4 + 0.3 if ilvl >= 835
    # opacity = ((ilvl - 850))*0.4 + 0.3 if ilvl >= 850
    # opacity = 0.3 if opacity < 0.3
    # opacity = 0.7 if opacity > 0.7

    # str = rbg + opacity.round(1).to_s + ")"
    # puts "\n\n\nSTR"
    # puts str
    # puts "---\n\n\n"

    return "background-color: " + rbg + ".5)"


  end

end

app/models/member.rb
class Member < ActiveRecord::Base

  has_many :items

  def self.refresh_data
    Member.all.each do |member|
      member.pull_data(Member.access_token)
    end
  end

  def self.access_token
    auth_url = 'https://us.battle.net/oauth/token?grant_type=client_credentials'
    auth_res = HTTParty.get(auth_url, basic_auth: {
      username: ENV['BNET_ID'],
      password: ENV['BNET_KEY']
    })
    JSON.parse(auth_res.body)['access_token']
  end

  def pull_data(access_token=nil)
    access_token ||= Member.access_token
    uri = Addressable::URI.parse("https://us.api.blizzard.com/profile/wow/character/kelthuzad/#{self.name.downcase}/equipment?namespace=profile-us&locale=en_US&access_token=#{access_token}")
    response = HTTParty.get(uri.normalize)
    data = JSON.parse(response.body)

    data["equipped_items"].each do |item|
      next unless Item.slots.include?(item["slot"]["type"].downcase.to_sym)
      existing_item = Item.where(member_id: id, slot: item["slot"]["type"].downcase).first rescue nil

      item_params = {
        item_id: item["item"]["id"],
        member_id: id,
        name: item["name"],
        ilvl: item["level"]["value"],
        slot: item["slot"]["type"].downcase,
        # enchant: (item_data["tooltipParams"]["enchant"] rescue nil),
        # gem0: (item_data["tooltipParams"]["gem0"] rescue nil),
        # gem1: (item_data["tooltipParams"]["gem1"] rescue nil),
        # gem2: (item_data["tooltipParams"]["gem2"] rescue nil),
        # bonus: (item_data["bonusLists"].first rescue nil)
      }

      if existing_item
        existing_item.update(item_params)
      else
        Item.create(item_params)
      end
    end
  end

  def self.get_all_sims

    base_url = "http://fgguild.herokuapp.com/"
    # base_url = "http://localhost:3001/"

    uri = Addressable::URI.parse(base_url + "members/get_ids")
    response = HTTParty.get(uri.normalize)
    data = JSON.parse(response.body)

    data.each do |member|
      puts "\n\n\nMEMBER:"
      puts member[0]
      puts member[1]
      Member.get_sims(member[0], member[1])
      puts "\n\n\n"
    end

    return ""
  end

  def self.get_sims(id, name)
    value = `sh scripts/simcraft.sh #{name}`
    file = File.read("#{name}.json") rescue nil

    if file
      data = JSON.parse(file)

      puts "\n\n\nSIM:"
      dps = (data["sim"]["players"][0]["collected_data"]["dps"]["mean"]).to_f.to_i
      puts dps
      uri = Addressable::URI.parse("http://fgguild.herokuapp.com/members/#{id}/update_dps?dps=#{dps}")
      HTTParty.post(uri)

      # File.delete("#{name}.json")
    end
  end

  def self.get_all_sims_cloud
    Member.all.each do |member|
      # ./simc/engine/simc armory=us,kelthuzad,Dolfin calculate_scale_factors=1 json=tmp/reports/Dolfin.json html=tmp/reports/Dolfin.html iterations=400 report_details=0
      value = `sh scripts/simcraft_prod.sh #{member.name}`

      json_file = File.read("tmp/reports/#{member.name}.json") rescue nil
      html_file = File.read("tmp/reports/#{member.name}.html") rescue nil

      if json_file
        data = JSON.parse(json_file)

        puts "\n\n\nSIM:"
        dps = (data["sim"]["players"][0]["collected_data"]["dps"]["mean"]).to_f.to_i
        puts dps
        member.update(dps: dps)
      end

      if html_file
        member.update(sim_results: html_file)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guild_controller.rb
class GuildController < ApplicationController

  def show
    @new_member = Member.new
    @members = Member.all.order(ilvl: :desc)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  skip_before_action :verify_authenticity_token

  before_action :set_member, only: [:update, :destroy]
  before_action :set_members

  def show
    @member = Member.find(params[:id])
  end

  def ids
    render json: Member.all.map { |m| [m.id, m.name] }.to_h.as_json
  end

  def create
    @new_member = Member.new(member_params).save

    respond_to do |format|
      format.js{ render layout: false, file: "members/render_table", content_type: 'text/javascript' }
    end
  end

  def index
    Member.refresh_data

    respond_to do |format|
      format.js { render layout: false, file: "members/render_table", content_type: 'text/javascript' }
    end
  end

  def update
    if @member
      @member.pull_data
      respond_to do |format|
        format.js{ render layout: false, file: "members/render_table", content_type: 'text/javascript' }
      end
    end
  end

  def update_dps
    @member = Member.find(params[:id]) rescue nil
    if @member && params[:dps].present?
      @member.update(dps: params[:dps])
      render json: {}, status: :ok
    end

  end

  def update_sims
    @member = Member.find(params[:id]) rescue nil
    if @member && params[:sim_html].present?
      @member.update(sim_results: params[:sim_html])
      render json: {}, status: :ok
    end
  end

  def destroy
    if @member
      @member.destroy
      respond_to do |format|
        format.js{ render layout: false, file: "members/render_table", content_type: 'text/javascript' }
      end
    end
  end

  private

  def set_member
    @member = Member.find(params[:id]) rescue nil
  end

  def set_members
    @members = Member.all.order(ilvl: :desc)
  end

  def member_params
    params.require(:member).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guild_helper.rb
module GuildHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/guild/_guild_table.haml
%table
    %tr
        %th Name
        %th Role
        %th ilvl
        %th SimDPS
        -Item.slots.each do |slot|
            %th= slot.to_s.capitalize
        %th
    -@members.each do |member|
        -items = member.items.map{ |item| [item.slot, item] }.to_h
        %tr
            %td{class: member.class_id ? "class-color-#{member.class_id}" : ""}
                %b= link_to member.name.capitalize, "https://worldofwarcraft.com/en-us/character/us/kelthuzad/#{member.name.downcase}", {target: "_blank" }
            %td.light
                %b= member.role
            %td.light
                -if member.items.count > 0
                    %b= member.items.map(&:ilvl).sum / member.items.count
            %td.light
                - if member.dps
                    - dps = member.dps/1000
                    -if dps > 50
                        %b= "#{dps}k"
                    -else
                        = "-"
                - else
                    = "-"
            -Item.slots.each do |slot|
                -item = items[slot.to_s]
                -if item && item[:ilvl]
                    - color_for_ilvl = Item.color_for_ilvl(item[:ilvl])
                    %td{style: color_for_ilvl}
                        .container
                            %a{rel: "item=#{item.item_id}&bonus=#{item.bonus}"}= item[:ilvl]
                            - if (slot == :mainHand || slot == :offHand || slot == :finger1 || slot == :finger2) && item[:enchant]
                                .fa.fa-check-circle
                -else
                    %td
            %td.action-list
                .refresh.inline
                    = link_to member_path(member.id), method: :put, remote: true do
                        %i.fa.fa-refresh
                .delete.inline
                    = link_to member_path(member.id), method: :delete, remote: true do
                        %i.fa.fa-trash
:javascript
    $('th').click(function(){
        var table = $(this).parents('table').eq(0)
        var rows = table.find('tr:gt(0)').toArray().sort(comparer($(this).index()))
        this.asc = !this.asc
        if (!this.asc){rows = rows.reverse()}
        for (var i = 0; i < rows.length; i++){table.append(rows[i])}
    })
    function comparer(index) {
        return function(a, b) {
            var valA = getCellValue(a, index), valB = getCellValue(b, index)
            return $.isNumeric(valA) && $.isNumeric(valB) ? valA - valB : valA.toString().localeCompare(valB)
        }
    }
    function getCellValue(row, index){ return $(row).children('td').eq(index).text() }

app/views/guild/_new_member_form.haml
=form_for @new_member, remote: true do |f|
    = f.text_field :name, {placeholder: "Name..."}
    = f.select :role, options_for_select(["Tank", "Healer", "RDPS", "MDPS"])
    = f.submit

:javascript
    $(document).ready(function() {
        $('select').formSelect();
    });

app/views/guild/show.haml
.table-view
    %h2 Lemme run the numbers
    .light Click on your name for armory link
    .light Click on your dps for simcraft link
    .light Be sure to actually click 'logout' to force the armory to update
    .light Sims updated hourly

    .table-wrap
        = render partial: "guild_table"
    .table-actions
        .new-member-form.inline
            = render partial: "new_member_form"
        .refresh-all.inline
            = link_to "REFRESH ALL", members_path(), remote: true

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guild</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="//wow.zamimg.com/widgets/power.js"></script><script>var wowhead_tooltips = { "colorlinks": true, "iconizelinks": true, "renamelinks": true }</script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/create.js.haml
console.log("HIT HERE");
console.log("HIT HERE");
console.log("HIT HERE");
console.log("HIT HERE");
console.log("HIT HERE");
alert();
$(.table-wrap).html("#{escape_javascript(render partial: 'guild/guild_table')}");

app/views/members/destroy.js.haml
$('.table-wrap').html("#{escape_javascript(render partial: 'guild/guild_table')}");

app/views/members/index.js.haml
$('.table-wrap').html("#{escape_javascript(render partial: 'guild/guild_table')}");

app/views/members/render_table.js.haml
$('.table-wrap').html("#{escape_javascript(render partial: 'guild/guild_table')}");

app/views/members/show.haml
= raw @member.sim_results